### ISSUE TITLE
ctlrender tests not working on Windows

### ISSUE THREAD

**Issue by ThomasWilshaw** [ampas/CTL#113]
Currently the ctlrender tests fail on Windows as it relies on a bash script. Windows is able to run bash files now through WSL and I was able to get that working by adding an option to pass the full path to the ctlrender executable to CMake. Is that something you would want to do or is there a better way to get the ctlrender tests working on Windows?

**Comment by michaeldsmith** [comment]
when you install git for windows, I think git bash is installed along with it.  

![image](https://user-images.githubusercontent.com/37905569/210663892-81523e9f-4288-48f6-a54b-23f6d15ebdf7.png)

Using git bash on windows lets the test.sh bash script run, but it seems there are problems with the path to ctlrender.exe, 

When I type this `ctest -V -C Debug` in git bash for windows, the first 3 tests run successfully but then I get this error on the cltrender test:

`4: ./test.sh: line 30: C:/temp/ctl_where_to_build_the_binaries/ctlrender/Debug/ctlrender.exe: No such file or directory`

When running in git bash for windows, the paths are a little different, for example, the exe is actually here:

`/c/temp/ctl_where_to_build_the_binaries/ctlrender/Debug/ctlrender.exe`

and not here

`C:/temp/ctl_where_to_build_the_binaries/ctlrender/Debug/ctlrender.exe`

Maybe there is a way for to switch the path from `C:/` to `/c/` somehow in the test.sh script when running in windows?  

The windows github CI workflows are configured correctly to run the ctlrender tests, so that is another way to test it, but more cumbersome than running locally.  

Another way to fix this (but would be more work) could be to switch the ctlrender tests away from using the bash script test.sh and to just make a bunch of add_test() values to the `\unittest\ctlrender\CMakeLists.txt` file, similar to how `\unittest\IlmCtl\CMakeLists.txt` has the `add_test(IlmCtl IlmCtlTest)` line that calls the IlmCtlTest executable.

**Comment by ThomasWilshaw** [comment]
No worries, that's exacly the same issue and conclusion I was having only I was using WSL so the file path I needed to use was even more complicated.

To pass the argument to the test I added to following to the CMakeLists.txt in `unittest\ctlrender`:
```
if(!CTLRENDER_PATH)
    set(CTLRENDER_PATH, $<TARGET_FILE:ctlrender>)
endif()
```

and then pass `${CTLRENDER_PATH}` to the `test.sh` comamnd a few lines later. I can then pass the path to ctlrender when building CTL. It feels a bit hacky but with the way the tests are set up to run through the bash script I couldn't find a nicer way. 

I agree switching away from the bash script might be a nicer way to do things and make cross compatibilty a bit easier. I might have a go and see how it turns out.
